
#include "\a3\editor_f\data\scripts\dikCodes.h"

["nineliners & Notepad","nln_open_notepad_key", "OPEN NOTEPAD", {_this call nln_noteblock_fnc_open}, {}, [DIK_N, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_nineliner_cas_key", "OPEN 9-Liner CAS", {_this call nln_nineliner_cas_fnc_open}, {}, [DIK_C, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_nineliner_medv_key", "OPEN 9-Liner MEDIVAC", {_this call nln_nineliner_medv_fnc_open}, {}, [DIK_M, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_fiveliner_gcff_key", "OPEN 5-Liner GUNSHIP CALL FOR FIRE", {_this call nln_fiveliner_gcff_fnc_open}, {}, [DIK_G, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_cas_check_in_key", "OPEN CAS CHECK-IN BREEFING", {_this call nln_cas_check_in_fnc_open}, {}, [DIK_B, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_sheet_tlm_key", "OPEN TARGET-LOCATION-METHODS SHEET", {_this call nln_tlm_fnc_open}, {}, [DIK_T, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_sheet_ffe_key", "OPEN FIRE-FOR-EFFECT SHEET", {_this call nln_ffe_fnc_open}, {}, [DIK_F, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_sheet_mm_key", "OPEN MARKING-MISSION SHEET", {_this call nln_mm_fnc_open}, {}, [DIK_J, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_open_sheet_afm_key", "OPEN ADJUST-FIRE-MISSION SHEET", {_this call nln_afm_fnc_open}, {}, [DIK_A, [true, true, false]]] call CBA_fnc_addKeybind;
["nineliners & Notepad","nln_disable_controls_key", "DISABLE CONTROLS", {[] spawn {execVM "nln_nineliner_and_notepad\data\toggleControls.sqf";}}, {}, [DIK_P, [true, true, false]]] call CBA_fnc_addKeybind;


if (isNil {profileNamespace getVariable "nln_nineiners_and_notepad_version_03_used"}) exitWith
{
	profileNamespace setVariable ["nln_nineliners_and_notepad_version_03_used", true];


	profileNamespace setVariable ["nln_nineliner_cas_lastPage", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_0", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_1", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_2", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_3", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_4", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_5", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_6", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_7", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_8", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_9", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_10", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_11", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_12", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_13", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_14", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_16", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_17", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_18", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_19", nil];
	profileNamespace setVariable ["nln_nineliner_cas_pageText_20", nil];

	profileNamespace setVariable ["nln_nineliner_medv_lastPage", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_1", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_2", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_3", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_4", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_5", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_6", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_7", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_8", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_9", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_10", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_11", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_12", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_13", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_14", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_15", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_16", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_17", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_18", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_19", nil];
	profileNamespace setVariable ["nln_nineliner_medv_pageText_20", nil];

	profileNamespace setVariable ["nln_afm_lastPage", nil];
	profileNamespace setVariable ["nln_afm_pageText_1", nil];
	profileNamespace setVariable ["nln_afm_pageText_2", nil];
	profileNamespace setVariable ["nln_afm_pageText_3", nil];
	profileNamespace setVariable ["nln_afm_pageText_4", nil];
	profileNamespace setVariable ["nln_afm_pageText_5", nil];
	profileNamespace setVariable ["nln_afm_pageText_6", nil];
	profileNamespace setVariable ["nln_afm_pageText_7", nil];
	profileNamespace setVariable ["nln_afm_pageText_8", nil];
	profileNamespace setVariable ["nln_afm_pageText_9", nil];
	profileNamespace setVariable ["nln_afm_pageText_10", nil];
	profileNamespace setVariable ["nln_afm_pageText_11", nil];
	profileNamespace setVariable ["nln_afm_pageText_12", nil];
	profileNamespace setVariable ["nln_afm_pageText_13", nil];
	profileNamespace setVariable ["nln_afm_pageText_14", nil];
	profileNamespace setVariable ["nln_afm_pageText_15", nil];
	profileNamespace setVariable ["nln_afm_pageText_16", nil];
	profileNamespace setVariable ["nln_afm_pageText_17", nil];
	profileNamespace setVariable ["nln_afm_pageText_18", nil];
	profileNamespace setVariable ["nln_afm_pageText_19", nil];
	profileNamespace setVariable ["nln_afm_pageText_20", nil];

	profileNamespace setVariable ["nln_cas_check_in_lastPage", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_1", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_2", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_3", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_4", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_5", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_6", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_7", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_8", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_9", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_10", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_11", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_12", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_13", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_14", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_15", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_16", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_17", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_18", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_19", nil];
	profileNamespace setVariable ["nln_cas_check_in_pageText_20", nil];

	profileNamespace setVariable ["nln_ffe_lastPage", nil];
	profileNamespace setVariable ["nln_ffe_pageText_1", nil];
	profileNamespace setVariable ["nln_ffe_pageText_2", nil];
	profileNamespace setVariable ["nln_ffe_pageText_3", nil];
	profileNamespace setVariable ["nln_ffe_pageText_4", nil];
	profileNamespace setVariable ["nln_ffe_pageText_5", nil];
	profileNamespace setVariable ["nln_ffe_pageText_6", nil];
	profileNamespace setVariable ["nln_ffe_pageText_7", nil];
	profileNamespace setVariable ["nln_ffe_pageText_8", nil];
	profileNamespace setVariable ["nln_ffe_pageText_9", nil];
	profileNamespace setVariable ["nln_ffe_pageText_10", nil];
	profileNamespace setVariable ["nln_ffe_pageText_11", nil];
	profileNamespace setVariable ["nln_ffe_pageText_12", nil];
	profileNamespace setVariable ["nln_ffe_pageText_13", nil];
	profileNamespace setVariable ["nln_ffe_pageText_14", nil];
	profileNamespace setVariable ["nln_ffe_pageText_15", nil];
	profileNamespace setVariable ["nln_ffe_pageText_16", nil];
	profileNamespace setVariable ["nln_ffe_pageText_17", nil];
	profileNamespace setVariable ["nln_ffe_pageText_18", nil];
	profileNamespace setVariable ["nln_ffe_pageText_19", nil];
	profileNamespace setVariable ["nln_ffe_pageText_20", nil];

	profileNamespace setVariable ["nln_fiveliner_gcff_lastPage", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_1", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_2", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_3", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_4", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_5", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_6", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_7", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_8", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_9", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_10", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_11", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_12", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_13", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_14", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_15", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_16", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_17", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_18", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_19", nil];
	profileNamespace setVariable ["nln_fiveliner_gcff_pageText_20", nil];

	profileNamespace setVariable ["nln_mm_lastPage", nil];
	profileNamespace setVariable ["nln_mm_pageText_1", nil];
	profileNamespace setVariable ["nln_mm_pageText_2", nil];
	profileNamespace setVariable ["nln_mm_pageText_3", nil];
	profileNamespace setVariable ["nln_mm_pageText_4", nil];
	profileNamespace setVariable ["nln_mm_pageText_5", nil];
	profileNamespace setVariable ["nln_mm_pageText_6", nil];
	profileNamespace setVariable ["nln_mm_pageText_7", nil];
	profileNamespace setVariable ["nln_mm_pageText_8", nil];
	profileNamespace setVariable ["nln_mm_pageText_9", nil];
	profileNamespace setVariable ["nln_mm_pageText_10", nil];
	profileNamespace setVariable ["nln_mm_pageText_11", nil];
	profileNamespace setVariable ["nln_mm_pageText_12", nil];
	profileNamespace setVariable ["nln_mm_pageText_13", nil];
	profileNamespace setVariable ["nln_mm_pageText_14", nil];
	profileNamespace setVariable ["nln_mm_pageText_15", nil];
	profileNamespace setVariable ["nln_mm_pageText_16", nil];
	profileNamespace setVariable ["nln_mm_pageText_17", nil];
	profileNamespace setVariable ["nln_mm_pageText_18", nil];
	profileNamespace setVariable ["nln_mm_pageText_19", nil];
	profileNamespace setVariable ["nln_mm_pageText_20", nil];

	profileNamespace setVariable ["nln_noteblock_LastPage", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_1", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_2", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_3", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_4", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_5", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_6", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_7", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_8", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_9", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_10", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_11", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_12", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_13", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_14", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_15", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_16", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_17", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_18", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_19", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_20", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_21", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_22", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_23", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_24", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_25", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_26", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_27", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_28", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_29", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_30", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_31", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_32", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_33", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_34", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_35", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_36", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_37", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_38", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_39", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_40", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_41", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_42", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_43", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_44", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_45", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_46", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_47", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_48", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_49", nil];
	profileNamespace setVariable ["nln_noteblock_pageText_50", nil];

	profileNamespace setVariable ["nln_noteblock_pageText_50", "                 CHANGELOG                              28.02.2015 - V0.3                                                    -added: Target-Location-Methods-Help sheet      -added: Fire-For-Effect sheet                   -added: Adjust-Fire-Mission sheet               -added: Marking-Mission sheet                  -added: View Document while moving Function   -changed: Removed all items. So it's a client-            side mod now!              -changed: some textbox stuff                  -changed: Medivac nineliner doesn't saves after             clearing a page anymore.             -changed: New ReadMe in the forum post!:      http://forums.bistudio.com/showthread.php?188821-Ingame-nineliners-amp-Notepad"];
	HINT FORMAT ["Hey %1!\nThanks for installing version 0.3 of my nineliners & Notepad mod!\nIf you've already used this mod in an other version before, all saved pages have been cleared.\nThis had to be done, because there were some changes with the textboxes of some sheets.\nI'm sorry for all your lost notes!\nIf this is your first time using this mod, make sure to take a look at the BI-Forums post of the mod.\nThe newest changelog was added to page 50 of your Notepad.\n\nEnjoy the new Version,\n~Chief Wiggum", profileName];
};

nln_nineliners_and_notepad_currentResource = "";
